create table tb_order (id int8 generated by default as identity, description varchar(255), primary key (id));
create table tb_tracking (id int8 generated by default as identity, location varchar(255), moment timestamp, status int4, order_id int8, primary key (id));
alter table if exists tb_tracking add constraint FK97isci22y63nbbc0u0gkd5tu0 foreign key (order_id) references tb_order;
